In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [4]:
for e in A: print(e)

1
2
3


In [5]:
L.append(1)

In [6]:
L = L + [5]

In [7]:
A + A

array([2, 4, 6])

In [8]:
A

array([1, 2, 3])

In [9]:
A*2

array([2, 4, 6])

In [10]:
L*2

[1, 2, 3, 1, 5, 1, 2, 3, 1, 5]

In [11]:
A**2

array([1, 4, 9], dtype=int32)

In [12]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [13]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [14]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [15]:
np.floor(np.exp(A))

array([ 2.,  7., 20.])

In [65]:
a = np.array([1,0])

In [66]:
b = np.array([0,1])

In [40]:
np.dot(a,b)

11

In [41]:
dot = 0; k = [1,2]; l=[3,4]

In [42]:
for e,f in zip(k,l): dot += e*f

In [43]:
dot

11

In [46]:
(a*b).sum()

11

In [47]:
np.sum(a*b)

11

In [49]:
np.dot(a,b)

11

In [50]:
a.dot(b)

11

In [51]:
b.dot(a)

11

In [52]:
amag = np.sqrt(np.sum(a*a))

In [53]:
amag

2.23606797749979

In [55]:
amag = np.linalg.norm(a)

In [57]:
amag

2.23606797749979

In [67]:
cosangle = a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))

In [68]:
cosangle

0.0

In [69]:
np.arccos(cosangle) # It is in radiant (pai/2)

1.5707963267948966

In [96]:
## Dot product example and comparison of numpy and python list function

In [71]:
from datetime import datetime

In [79]:
def slow_dot(a, b):
    dot = 0 
    for c, d in zip(a,b):
        dot =+ c*d
    return dot

In [89]:
a = list(range(100))

In [90]:
b = list(range(100))

In [91]:
%timeit slow_dot(a,b)

12.2 µs ± 1.27 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [92]:
def fast_dot(a,b):
    return a.dot(b)

In [93]:
a = np.array(np.random.randint(100))

In [94]:
b = np.array(np.random.randint(100))

In [95]:
%timeit fast_dot(a,b)

1.16 µs ± 48.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## As we can see Numpy is approximately 10 times faster 

In [2]:
import numpy as np
M = np.array([[1,2], [3,4]])

In [3]:
M[0][1]

2

In [4]:
M[0,1]

2

In [7]:
M = np.matrix([[1,2],[3,4]])

In [8]:
M[0]

matrix([[1, 2]])

In [11]:
M[0][0]

matrix([[1, 2]])

In [10]:
M[0,0]

1

In [12]:
A = np.array(M)

In [13]:
A[0][0]

1

In [14]:
A[0,0]

1

In [15]:
A.T

array([[1, 3],
       [2, 4]])

In [16]:
M.T

matrix([[1, 3],
        [2, 4]])

In [18]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((1,1,2))

array([[[0., 0.]]])

In [25]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.random.random(10)

array([0.05292544, 0.07101248, 0.46763016, 0.51585798, 0.67046228,
       0.33622727, 0.67604334, 0.86374407, 0.64777695, 0.20277141])

In [29]:
np.random.random((10,10))

array([[0.11020876, 0.39518587, 0.33247225, 0.6501349 , 0.00974722,
        0.95411243, 0.99122364, 0.53202145, 0.48342393, 0.99840053],
       [0.5061127 , 0.09421543, 0.70212733, 0.58619282, 0.4837725 ,
        0.25775481, 0.88026589, 0.29060458, 0.7393046 , 0.50892163],
       [0.57779112, 0.83617291, 0.41782077, 0.96640016, 0.71687923,
        0.65928184, 0.09676119, 0.60459043, 0.11353212, 0.55293491],
       [0.14396082, 0.95501762, 0.99490097, 0.91372575, 0.55425136,
        0.34334408, 0.9667448 , 0.50053685, 0.05729069, 0.07617157],
       [0.60524839, 0.02704272, 0.50239407, 0.60944942, 0.61810038,
        0.302902  , 0.64906463, 0.74539516, 0.27517568, 0.33384196],
       [0.7801444 , 0.31467271, 0.55544782, 0.56628261, 0.37374022,
        0.03106553, 0.55386632, 0.51032621, 0.55066675, 0.2287297 ],
       [0.74267316, 0.60176475, 0.0603174 , 0.69906928, 0.65193947,
        0.66777833, 0.10200996, 0.57743295, 0.19629575, 0.39853842],
       [0.13304246, 0.95289279, 0.4201987

In [30]:
G = np.random.randn(10)

In [31]:
G

array([-0.41689482, -0.11862028, -0.23676492,  1.63942843,  0.84127395,
        0.36097427, -2.02333672, -0.6766474 , -0.69955188, -0.33762046])

In [32]:
np.random.randn(10,10)

array([[-2.33537723e-01, -1.45451175e+00,  1.52330077e-01,
        -3.39862548e-01,  1.47272882e+00, -2.09194169e-01,
         1.43638839e+00, -1.90261380e-01,  5.46945559e-01,
         2.05300581e-01],
       [ 2.00125655e+00,  3.18942051e-01, -7.61147700e-01,
         2.23327447e+00, -8.74274895e-01,  1.03866274e+00,
        -9.34536759e-01,  8.13593726e-01,  3.62944444e-01,
        -6.58135171e-01],
       [-3.06874188e-01, -1.54835452e-01,  1.04326592e+00,
         1.06420171e+00, -6.77826397e-01,  1.91176424e-01,
         2.91866009e-01, -1.47540586e+00,  6.42965298e-01,
        -8.72776526e-02],
       [ 3.47335058e-01,  3.30767472e-01,  2.44202072e+00,
        -1.65084194e+00, -9.53035791e-01,  1.56585878e-02,
         7.30657255e-02,  3.93015611e-01, -1.25933802e+00,
        -3.91357255e-01],
       [ 1.27031283e+00,  2.09582355e+00,  1.91165199e-01,
         2.65892479e-01,  1.29134779e+00, -4.26952031e-04,
         2.80430353e-01,  8.24098148e-02, -3.31716316e-01,
        -5.

In [33]:
G.mean()

-0.16677598363502089

In [34]:
G.var()

0.8646660847197781

In [35]:
A = np.array([[1,2], [3,4]])

In [37]:
Ainv = np.linalg.inv(A)

In [38]:
A.dot(Ainv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [39]:
Ainv.dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [40]:
np.linalg.det(A)

-2.0000000000000004

In [41]:
np.diag(A)

array([1, 4])

In [43]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [44]:
np.diag([[1,2],[3,4]])

array([1, 4])

In [45]:
a = np.array([1,2])

In [46]:
b = np.array([3,4])

In [47]:
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [48]:
np.inner(a,b)

11

In [49]:
a.dot(b)

11

In [52]:
np.diag(A).sum()

5

In [53]:
np.trace(A)

5

In [57]:
X = np.random.randn(100,3)

In [58]:
X

array([[ 0.8405849 , -0.6686932 , -1.28643092],
       [-0.48793077,  1.40725623, -0.16322965],
       [ 0.61515691, -1.89633663, -2.43948352],
       [-0.79853431, -1.14787083, -0.54697406],
       [-1.58478019,  1.22429423, -0.50681401],
       [ 0.37256637, -0.78738219, -0.74886634],
       [-0.9696492 ,  1.86722832, -1.57255066],
       [ 1.71774737, -0.4305711 , -1.46755787],
       [-0.2147326 ,  1.07919699, -0.51179169],
       [ 0.55680477, -0.39386467,  1.04200878],
       [-0.53158509,  0.64002774, -1.00691108],
       [ 0.83367862,  1.08849242, -0.13090064],
       [-0.70043058, -1.1755053 , -0.12803209],
       [ 1.2928966 ,  1.13711856, -0.84006282],
       [ 0.48127158, -0.65713504,  0.74042113],
       [ 0.2619297 , -0.58009268,  2.55800708],
       [ 0.47063236, -0.92363157, -0.30742648],
       [ 0.46353732,  0.49750815,  0.95988682],
       [-1.62888174, -0.93064827,  0.74986652],
       [ 0.42470239,  0.16967695,  1.30249242],
       [ 2.12060286, -0.67344943, -0.530

In [66]:
cov = np.cov(X.T)

In [67]:
np.linalg.eig(cov)

(array([1.18627439, 0.94743277, 0.81150117]),
 array([[ 0.47684345, -0.86874752, -0.13378369],
        [-0.20413505,  0.03858926, -0.97818186],
        [-0.85495568, -0.49374955,  0.15894078]]))

In [68]:
np.linalg.eigh(cov)

(array([0.81150117, 0.94743277, 1.18627439]),
 array([[-0.13378369,  0.86874752, -0.47684345],
        [-0.97818186, -0.03858926,  0.20413505],
        [ 0.15894078,  0.49374955,  0.85495568]]))

## AX = b

In [70]:
A = np.array([[1,2], [3,4]])

In [71]:
b = np.array([3,4])

In [72]:
x = np.linalg.inv(A).dot(b)

In [73]:
x

array([-2. ,  2.5])

In [74]:
x = np.linalg.solve(A, b)

In [75]:
x

array([-2. ,  2.5])

# X1 + X2 = 2200 and 1.5X1 + 4X2 = 5050 whats the value of x1 and x2

In [79]:
np.linalg.solve(np.array([[1,1],[1.5, 4]]), np.array([2200, 5050]))

array([1500.,  700.])